/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontend;

import ConnectionSQL.ConClient;
import java.util.LinkedList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chejohrpp
 */
public class CatalogoProd extends javax.swing.JFrame {
    private DefaultTableModel dfm = new DefaultTableModel();
    String colum = null;
    String param = null;
    LinkedList codigo = new LinkedList();
    LinkedList nombre = new LinkedList();
    LinkedList fab = new LinkedList();
    LinkedList precio = new LinkedList();
    LinkedList cant = new LinkedList();
    LinkedList tienda = new LinkedList();
    
    /**
     * Creates new form CatalogoProd
     */
    public CatalogoProd() {
        initComponents();
        dfm = (DefaultTableModel) jList.getModel();
    }
     private void generar(){
         //Limpiar listado
       int cantRow = jList.getRowCount();
        for (int i = cantRow-1; i >= 0; i--) {
            dfm.removeRow(i);
        }
        
        //Agregar listado
        while (codigo.peek() != null) {            
                String data[] = {(String)codigo.poll(),(String)nombre.poll(),(String)fab.poll(),(String)precio.poll(),
                    (String)cant.poll(),(String)tienda.poll()};
                dfm.addRow(data);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OnlyGroup = new javax.swing.ButtonGroup();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList = new javax.swing.JTable();
        btnCod = new javax.swing.JButton();
        txtCod = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnName = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnFab = new javax.swing.JButton();
        txtFab = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        rbtnFab = new javax.swing.JRadioButton();
        rbtnName = new javax.swing.JRadioButton();
        rbtnPre = new javax.swing.JRadioButton();
        rbtnCod = new javax.swing.JRadioButton();
        rbtnCant = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        rbtnFab1 = new javax.swing.JRadioButton();
        rbtnName1 = new javax.swing.JRadioButton();
        rbtnPre1 = new javax.swing.JRadioButton();
        rbtnCod1 = new javax.swing.JRadioButton();
        rbtnCant1 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();

        jButton2.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jButton2.setText("Regresar");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Fabricante", "Precio", "Cantidad", "Tienda"
            }
        ));
        jScrollPane1.setViewportView(jList);

        btnCod.setText("Buscar");
        btnCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCodActionPerformed(evt);
            }
        });

        jLabel1.setText("Buscar por nombre");

        btnName.setText("Buscar");
        btnName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNameActionPerformed(evt);
            }
        });

        jLabel2.setText("Buscar por codigo");

        jLabel3.setText("Buscar por fabricante");

        btnFab.setText("Buscar");
        btnFab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFabActionPerformed(evt);
            }
        });

        OnlyGroup.add(rbtnFab);
        rbtnFab.setText("Fabricante");
        rbtnFab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnFabActionPerformed(evt);
            }
        });

        OnlyGroup.add(rbtnName);
        rbtnName.setText("Nombre");
        rbtnName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnNameActionPerformed(evt);
            }
        });

        OnlyGroup.add(rbtnPre);
        rbtnPre.setText("Precio");
        rbtnPre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnPreActionPerformed(evt);
            }
        });

        OnlyGroup.add(rbtnCod);
        rbtnCod.setText("Codigo");
        rbtnCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnCodActionPerformed(evt);
            }
        });

        OnlyGroup.add(rbtnCant);
        rbtnCant.setText("Cantidad");
        rbtnCant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnCantActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtnCant)
                    .addComponent(rbtnCod)
                    .addComponent(rbtnPre)
                    .addComponent(rbtnName)
                    .addComponent(rbtnFab))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtnName)
                .addGap(18, 18, 18)
                .addComponent(rbtnFab)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtnCod)
                .addGap(18, 18, 18)
                .addComponent(rbtnPre)
                .addGap(18, 18, 18)
                .addComponent(rbtnCant)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        OnlyGroup.add(rbtnFab1);
        rbtnFab1.setText("Fabricante");
        rbtnFab1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnFab1ActionPerformed(evt);
            }
        });

        OnlyGroup.add(rbtnName1);
        rbtnName1.setText("Nombre");
        rbtnName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnName1ActionPerformed(evt);
            }
        });

        OnlyGroup.add(rbtnPre1);
        rbtnPre1.setText("Precio");
        rbtnPre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnPre1ActionPerformed(evt);
            }
        });

        OnlyGroup.add(rbtnCod1);
        rbtnCod1.setText("Codigo");
        rbtnCod1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnCod1ActionPerformed(evt);
            }
        });

        OnlyGroup.add(rbtnCant1);
        rbtnCant1.setText("Cantidad");
        rbtnCant1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnCant1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtnCant1)
                    .addComponent(rbtnCod1)
                    .addComponent(rbtnPre1)
                    .addComponent(rbtnName1)
                    .addComponent(rbtnFab1))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtnName1)
                .addGap(18, 18, 18)
                .addComponent(rbtnFab1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtnCod1)
                .addGap(18, 18, 18)
                .addComponent(rbtnPre1)
                .addGap(18, 18, 18)
                .addComponent(rbtnCant1)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jLabel4.setText("Ordenar de manera:");

        jLabel5.setText("Descendente");

        jLabel6.setText("Ascendente");

        btnRegresar.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnCod)
                                    .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnFab)
                                    .addComponent(txtFab, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnName)
                                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5)
                                        .addGap(92, 92, 92))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(btnRegresar))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnName)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCod)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtFab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnFab)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(29, 29, 29)
                        .addComponent(btnRegresar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCodActionPerformed
        // TODO add your handling code here:
        try{
            colum = "codigo";
           param = txtCod.getText();
           ConClient clie = new ConClient();
           clie.buscarProd(colum, param, codigo, nombre, fab, precio, cant, tienda);
            generar();
        }catch(Exception e){

        }
    }//GEN-LAST:event_btnCodActionPerformed

    private void btnNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNameActionPerformed
        // TODO add your handling code here:
        try{
            colum = "nombre";
           param = txtName.getText();
           ConClient clie = new ConClient();
           clie.buscarProd(colum, param, codigo, nombre, fab, precio, cant, tienda);

            generar();
        }catch(Exception e){

        }
    }//GEN-LAST:event_btnNameActionPerformed

    private void btnFabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFabActionPerformed
        // TODO add your handling code here:
        try{
            colum = "fabricante";
            param = txtFab.getText();
            ConClient clie = new ConClient();
            clie.buscarProd(colum, param, codigo, nombre, fab, precio, cant, tienda);
            generar();
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_btnFabActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        OpcionCliente op = new OpcionCliente();
        op.setLocationRelativeTo(null);
        op.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void rbtnNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnNameActionPerformed
        // TODO add your handling code here:
        String order = "p.nombre";
        ConClient clie = new ConClient();
        clie.ordenarProd(order, colum, param, codigo, nombre, fab, precio, cant, tienda);
        generar();
    }//GEN-LAST:event_rbtnNameActionPerformed

    private void rbtnFabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnFabActionPerformed
        // TODO add your handling code here:
        String order = "p.fabricante";
        ConClient clie = new ConClient();
        clie.ordenarProd(order, colum, param, codigo, nombre, fab, precio, cant, tienda);
        generar();
        
    }//GEN-LAST:event_rbtnFabActionPerformed

    private void rbtnCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnCodActionPerformed
        // TODO add your handling code here:
        String order = "p.codigo";
        ConClient clie = new ConClient();
        clie.ordenarProd(order, colum, param, codigo, nombre, fab, precio, cant, tienda);
        generar();
    }//GEN-LAST:event_rbtnCodActionPerformed

    private void rbtnPreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnPreActionPerformed
        // TODO add your handling code here:
        String order = "p.precio";
        ConClient clie = new ConClient();
        clie.ordenarProd(order, colum, param, codigo, nombre, fab, precio, cant, tienda);
        generar();
    }//GEN-LAST:event_rbtnPreActionPerformed

    private void rbtnCantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnCantActionPerformed
        // TODO add your handling code here:
        String order = "pt.cantidad";
        ConClient clie = new ConClient();
        clie.ordenarProd(order, colum, param, codigo, nombre, fab, precio, cant, tienda);
        generar();
    }//GEN-LAST:event_rbtnCantActionPerformed

    private void rbtnName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnName1ActionPerformed
        // TODO add your handling code here:
        String order = "p.nombre";
        ConClient clie = new ConClient();
        clie.ordenarProdDesc(order, colum, param, codigo, nombre, fab, precio, cant, tienda);
        generar();
    }//GEN-LAST:event_rbtnName1ActionPerformed

    private void rbtnFab1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnFab1ActionPerformed
        // TODO add your handling code here:
        String order = "p.fabricante";
        ConClient clie = new ConClient();
        clie.ordenarProdDesc(order, colum, param, codigo, nombre, fab, precio, cant, tienda);
        generar();
    }//GEN-LAST:event_rbtnFab1ActionPerformed

    private void rbtnCod1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnCod1ActionPerformed
        // TODO add your handling code here:
        String order = "p.codigo";
        ConClient clie = new ConClient();
        clie.ordenarProdDesc(order, colum, param, codigo, nombre, fab, precio, cant, tienda);
        generar();
    }//GEN-LAST:event_rbtnCod1ActionPerformed

    private void rbtnPre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnPre1ActionPerformed
        // TODO add your handling code here:
        String order = "p.precio";
        ConClient clie = new ConClient();
        clie.ordenarProdDesc(order, colum, param, codigo, nombre, fab, precio, cant, tienda);
        generar();
    }//GEN-LAST:event_rbtnPre1ActionPerformed

    private void rbtnCant1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnCant1ActionPerformed
        // TODO add your handling code here:
        String order = "pt.cantidad";
        ConClient clie = new ConClient();
        clie.ordenarProdDesc(order, colum, param, codigo, nombre, fab, precio, cant, tienda);
        generar();
    }//GEN-LAST:event_rbtnCant1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup OnlyGroup;
    private javax.swing.JButton btnCod;
    private javax.swing.JButton btnFab;
    private javax.swing.JButton btnName;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTable jList;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbtnCant;
    private javax.swing.JRadioButton rbtnCant1;
    private javax.swing.JRadioButton rbtnCod;
    private javax.swing.JRadioButton rbtnCod1;
    private javax.swing.JRadioButton rbtnFab;
    private javax.swing.JRadioButton rbtnFab1;
    private javax.swing.JRadioButton rbtnName;
    private javax.swing.JRadioButton rbtnName1;
    private javax.swing.JRadioButton rbtnPre;
    private javax.swing.JRadioButton rbtnPre1;
    private javax.swing.JTextField txtCod;
    private javax.swing.JTextField txtFab;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
