/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontend;

import ConnectionSQL.AgregarDB;
import ConnectionSQL.ConnectionDB;
import ConnectionSQL.ModDB;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author chejohrpp
 */
public class NewEmp extends javax.swing.JFrame {
    private boolean ingreso = true;
    /**
     * Creates new form NewEmp
     */
    public NewEmp() {
        ingreso = true;
        initComponents();
    }
    public NewEmp(String titulo) {
        ingreso = false;
        initComponents();
        lblTituloEmp.setText(titulo);
        txtCod.setEnabled(false);
        btnIngresar.setText("Guardar Cambios");
        buscarEmp();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        lblTituloEmp = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCod = new javax.swing.JTextField();
        txtNIT = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        txtDPI = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        txtTel = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabel5.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel5.setText("Telefono*");

        jLabel6.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel6.setText("DPI*");

        btnIngresar.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        lblTituloEmp.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        lblTituloEmp.setText("Ingreso de nuevo Empleado");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel2.setText("Codigo*");

        jLabel7.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel7.setText("Correo electronico*");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel3.setText("Nombre*");

        jLabel9.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel9.setText("NIT");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel4.setText("Direccion*");

        jLabel8.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel8.setText("* campos obligatorios");

        btnCancelar.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        btnCancelar.setText("Regresar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5))
                            .addGap(148, 148, 148))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(175, 175, 175)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDireccion)
                    .addComponent(txtName)
                    .addComponent(txtCod)
                    .addComponent(txtEmail)
                    .addComponent(txtNIT)
                    .addComponent(txtDPI)
                    .addComponent(txtTel))
                .addGap(214, 214, 214))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(lblTituloEmp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(381, 381, 381)
                        .addComponent(btnIngresar)
                        .addGap(47, 47, 47)
                        .addComponent(btnCancelar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(lblTituloEmp))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtDPI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtNIT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(203, 203, 203)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIngresar)
                    .addComponent(btnCancelar))
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        OpcionEmp op_emp = new OpcionEmp();
        op_emp.setLocationRelativeTo(null);
        this.dispose();
        op_emp.setVisible(true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:
        try{
            String codigo = txtCod.getText();
            String nombre = txtName.getText();
            String tel = txtTel.getText();
            String dpi = txtDPI.getText();
            String dir = txtDireccion.getText();
            String nit = txtNIT.getText();
            String email = txtEmail.getText();
            
            if (isEmpty(dpi,email,dir)) {
                 JOptionPane.showMessageDialog(null, "Ingrese bien los datos \nFaltan datos por llenar", "ERORR", JOptionPane.ERROR_MESSAGE);
                throw new IllegalArgumentException("Faltan datos por llenar");
            }
            if (ingreso) {
                ingresar(nombre,codigo,tel,dpi,dir,nit,email);
            }else{
                mod(nombre,codigo,tel,dpi,dir,nit,email);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Ingrese bien los datos", "ERORR", JOptionPane.ERROR_MESSAGE);
            System.out.println(e.getMessage());   
        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    private boolean isEmpty(String dpi, String email, String dir) {
        dpi = dpi.replaceAll("^\\s*","");
        dpi = dpi.replaceAll("\\s*$","");
        email = email.replaceAll("^\\s*","");
        email = email.replaceAll("\\s*$","");
        dir = dir.replaceAll("^\\s*","");
        dir = dir.replaceAll("\\s*$","");
        return (dpi.equalsIgnoreCase("") || email.equalsIgnoreCase("") || dir.equalsIgnoreCase(""));
    }
    private void ingresar(String nombre,String cod, String tel,String dpi,String dir, String nit, String email){
        try{
            AgregarDB agregar = new  AgregarDB();
            agregar.addEmp(this,cod, nombre, tel, dpi, nit, email, dir);
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }
    private void mod(String nombre,String cod, String tel,String dpi,String dir, String nit, String email){
        try{
            ModDB mod = new ModDB();
            mod.modEmp(this,cod, nombre, tel, dpi, nit, email, dir);
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }
    private void buscarEmp(){
        ConnectionDB con = new ConnectionDB();       
        try( Connection connection = con.getConnection()){
            String query = "SELECT codigo FROM empleado"; 
            
            try(PreparedStatement preSt = connection.prepareStatement(query)){
                ResultSet result = preSt.executeQuery();
                JComboBox camEmp = new JComboBox();//creamos un JComboBox
                //agregamos los nombres al JComboBox
                while(result.next()){
                    camEmp.addItem(result.getString(1));
                }
                //hacemos que el usuario seleccione el empleado
                //camEmp.setEditable(true);
                JOptionPane.showMessageDialog(null, camEmp, "Seleccione el codigo del empleado", JOptionPane.QUESTION_MESSAGE);
                String codigo = camEmp.getSelectedItem().toString();
                //colocamos el codigo en la caja de texto
                txtCod.setText(codigo);
                llenar(codigo,connection);
                result.close();
                con.closeConnection();//cerramos conexion
            }catch(SQLException e){
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(OpcionEmp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
      private void llenar(String codigo,Connection connection){
        String query = "SELECT nombre,telefono,dpi,direccion,email,nit from empleado WHERE codigo= ?";
        try(PreparedStatement preSt = connection.prepareStatement(query)){
            preSt.setString(1, codigo);
            
            ResultSet result = preSt.executeQuery();            
            //agregamos los datos a los text Field
            if (result.next()) {
                txtName.setText(result.getString(1));
                txtTel.setText(result.getString(2));
                txtDPI.setText(result.getString(3));
                txtDireccion.setText(result.getString(4));
                txtEmail.setText(result.getString(5));
                txtNIT.setText(result.getString(6));
                
            } 
            result.close();
        }catch(SQLException e){
            System.out.println(e.getMessage());
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblTituloEmp;
    private javax.swing.JTextField txtCod;
    private javax.swing.JTextField txtDPI;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNIT;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtTel;
    // End of variables declaration//GEN-END:variables
}
