/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontend;

import ConnectionSQL.AgregarDB;
import ConnectionSQL.ConsultasVarias;
import ConnectionSQL.ModDB;
import static Frontend.SignEmp.tienda_actual;
import java.sql.Date;
import java.util.Calendar;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chejohrpp
 */
public class NewPedido extends javax.swing.JFrame {
 private DefaultTableModel dfm = new DefaultTableModel();
 private double total;
 private double anticipo;
 private double cred;
 private int dias;
 private LinkedList cod = new LinkedList();
 private LinkedList cant = new LinkedList();
 private LinkedList exisst = new LinkedList();
    /**
     * Creates new form Venta
     */
    public NewPedido() {
        initComponents();
        
        agregarTienda();
        agregarProd();
        agregarNIt();
        agregarRes();
        dfm = (DefaultTableModel) jList.getModel();
        
    }
    private void agregarTienda(){
        ConsultasVarias consulta = new ConsultasVarias();
        LinkedList tiendas = consulta.codTiendas(tienda_actual);
        while(tiendas.peek() != null){
            String data = (String) tiendas.poll();
            cmbTienda.addItem(data);
           
        }
    }
    private void agregarProd(){
        cmbProd.removeAllItems();
        ConsultasVarias consulta = new ConsultasVarias();
        LinkedList productos = consulta.codProds(cmbTienda.getSelectedItem().toString());
        while(productos.peek() != null){
            String data = (String) productos.poll();
            cmbProd.addItem(data);
        }
    }
    private void agregarNIt(){
        cmbClient.removeAllItems();
        ConsultasVarias consulta = new ConsultasVarias();
        LinkedList nit = consulta.nitClient();
        while(nit.peek() != null){
            String data = (String) nit.poll();
            cmbClient.addItem(data);
        }
    }
    private void agregarRes(){
        ConsultasVarias consulta = new ConsultasVarias();
        lblExist.setText(String.valueOf("Existencias: "+consulta.exist(cmbTienda.getSelectedItem().toString(), cmbProd.getSelectedItem().toString())));
        dias = consulta.fechaE(cmbTienda.getSelectedItem().toString());
        lblDate.setText(String.valueOf("Tiempo en dias estimado: "+dias));
        cred = consulta.cred(cmbClient.getSelectedItem().toString());
        lblCred.setText(String.valueOf("Credito máximo del cliente: "+cred));
        lblPrecio.setText("Precio: "+String.valueOf(consulta.precio(cmbProd.getSelectedItem().toString())));
    }
    
    private void generar(){        
        //Agregar listado
        try{
            ConsultasVarias consulta = new ConsultasVarias();
             int cantidad = Integer.parseInt(txtCant.getText());
             int exist = consulta.exist(cmbTienda.getSelectedItem().toString(), cmbProd.getSelectedItem().toString());
            if (cantidad <= exist) {
                cod.offer(cmbProd.getSelectedItem().toString());          
                cant.offer(cantidad);
                int rest = exist-cantidad;
                exisst.offer(rest);
                calc(cantidad,consulta.precio(cmbProd.getSelectedItem().toString()));
                String data[] = {cmbProd.getSelectedItem().toString(),String.valueOf(consulta.precio(cmbProd.getSelectedItem().toString())),String.valueOf(cantidad)};
                dfm.addRow(data);
                cmbTienda.setEnabled(false);
            }else{
                JOptionPane.showMessageDialog(null, "No hay muchas existencias", "ERORR", JOptionPane.ERROR_MESSAGE);
            }
            
        } catch(Exception e){
           JOptionPane.showMessageDialog(null, "Ingrese los datos", "ERORR", JOptionPane.ERROR_MESSAGE);  

        }      
        
    }
    
    private void calc(int cant, double precio){
        total += cant*precio;
        anticipo = total*0.25;
        
        lblTotal.setText("Total: " + String.valueOf(total));
        lblAnt.setText("anticipo minimo: " + String.valueOf(anticipo));
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbTienda = new javax.swing.JComboBox<>();
        btnCofirm = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        cmbProd = new javax.swing.JComboBox<>();
        txtEFect = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lblExist = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        lblAnt = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cmbClient = new javax.swing.JComboBox<>();
        lblDate = new javax.swing.JLabel();
        txtCred = new javax.swing.JTextField();
        txtCant = new javax.swing.JTextField();
        lblCred = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        lblPrecio = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabel1.setText("Tienda de origen");

        cmbTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTiendaActionPerformed(evt);
            }
        });

        btnCofirm.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        btnCofirm.setText("Confirmar");
        btnCofirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCofirmActionPerformed(evt);
            }
        });

        jList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Cantidad", "Precio"
            }
        ));
        jList.setToolTipText("");
        jScrollPane1.setViewportView(jList);

        jLabel2.setText("Producto");

        cmbProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProdActionPerformed(evt);
            }
        });

        jLabel3.setText("Cantidad");

        lblExist.setText("Existencia: 987");

        btnAdd.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btnAdd.setText("Agregar");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        lblAnt.setText("Anticipo minimo: 000");

        jLabel6.setText("Pago en efectivo");

        jLabel7.setText("Pago con credito");

        jLabel8.setText("Cliente");

        cmbClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbClientActionPerformed(evt);
            }
        });

        lblDate.setText("Fecha estimada de entrega: 20122/02/02");

        lblCred.setText("Credito Maximo:");

        btnRegresar.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        lblPrecio.setText("Precio:000");

        lblTotal.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblTotal.setText("Total:000");

        jLabel4.setText("Coloque 0 si no va a pagar en una casilla");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(btnCofirm)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRegresar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblPrecio)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblExist))
                                    .addComponent(cmbTienda, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbProd, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtEFect)
                                    .addComponent(txtCred)
                                    .addComponent(txtCant)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblTotal)
                                            .addComponent(lblCred))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4)))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(btnAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(113, Short.MAX_VALUE)
                        .addComponent(lblDate)
                        .addGap(110, 110, 110))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAnt)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(cmbClient, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cmbTienda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cmbProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCant))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblExist)
                            .addComponent(lblPrecio))
                        .addGap(34, 34, 34)
                        .addComponent(btnAdd)
                        .addGap(18, 18, 18)
                        .addComponent(lblDate)
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cmbClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAnt)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtEFect))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtCred))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCred)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addComponent(lblTotal)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCofirm)
                            .addComponent(btnRegresar)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        OpcionEmp emp = new OpcionEmp();
        emp.setLocationRelativeTo(null);
        emp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void cmbTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTiendaActionPerformed
        // TODO add your handling code here:
        agregarProd();
        ConsultasVarias consulta = new ConsultasVarias();
        dias = consulta.fechaE(cmbTienda.getSelectedItem().toString());
        lblDate.setText(String.valueOf("Tiempo en dias estimado: "+dias));
    }//GEN-LAST:event_cmbTiendaActionPerformed

    private void cmbClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbClientActionPerformed
        // TODO add your handling code here:
        if (cmbClient.getSelectedIndex() != -1) {
            ConsultasVarias consulta = new ConsultasVarias();
            cred = consulta.cred(cmbClient.getSelectedItem().toString());
            lblCred.setText(String.valueOf("Credito máximo del cliente: "+cred));
        }
        
    }//GEN-LAST:event_cmbClientActionPerformed

    private void cmbProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProdActionPerformed
        // TODO add your handling code here:
        if (cmbProd.getSelectedIndex() != -1) {
            ConsultasVarias consulta = new ConsultasVarias();
            lblExist.setText(String.valueOf("Existencias: "+consulta.exist(cmbTienda.getSelectedItem().toString(), cmbProd.getSelectedItem().toString())));
            lblPrecio.setText("Precio: "+String.valueOf(consulta.precio(cmbProd.getSelectedItem().toString())));
        }
        
    }//GEN-LAST:event_cmbProdActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        generar();
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnCofirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCofirmActionPerformed
        // TODO add your handling code here:
        try{
            double quitCred = Double.parseDouble(txtCred.getText());
            double efect = Double.parseDouble(txtEFect.getText());
            double ant = quitCred+efect;
            
            if (quitCred <= cred) {
                if (ant >= anticipo) {
                    AgregarDB agregar = new AgregarDB();  
                    agregar.addPedido(cmbTienda.getSelectedItem().toString(), tienda_actual, dias, cmbClient.getSelectedItem().toString(), total, ant);
                     ConsultasVarias consulta = new ConsultasVarias();
                     int cod_ped = consulta.lastPedido();
                    while(cod.peek() != null){
                        AgregarDB agregar1 = new AgregarDB();                          
                        agregar1.addPedidoProducto((String) cod.poll(), cod_ped, (int) cant.poll(), (int) exisst.poll(), cmbTienda.getSelectedItem().toString());
                    }                    
                    ModDB mod = new ModDB();
                    mod.modCred(cred-quitCred, cmbClient.getSelectedItem().toString());
                    
                    //JOptionPane.showMessageDialog(null, "Pedido confirmado", "Finalizado Exitoso", JOptionPane.INFORMATION_MESSAGE);
                    OpcionEmp emp = new OpcionEmp();
                    emp.setLocationRelativeTo(null);
                    emp.setVisible(true);
                    this.dispose();
                }else{
                    JOptionPane.showMessageDialog(null, "el anticipo es menor al minimo", "ERORR", JOptionPane.ERROR_MESSAGE);
                }        
            }else{
                JOptionPane.showMessageDialog(null, "supera el limite de uso en el credito", "ERORR", JOptionPane.ERROR_MESSAGE);
            }
        }catch(Exception e){
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(null, "no se ha podido completar la tarea, verifique los datos", "ERORR", JOptionPane.ERROR_MESSAGE);  
        }
    }//GEN-LAST:event_btnCofirmActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCofirm;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cmbClient;
    private javax.swing.JComboBox<String> cmbProd;
    private javax.swing.JComboBox<String> cmbTienda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTable jList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAnt;
    private javax.swing.JLabel lblCred;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblExist;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTextField txtCant;
    private javax.swing.JTextField txtCred;
    private javax.swing.JTextField txtEFect;
    // End of variables declaration//GEN-END:variables
}
