/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontend;

import ConnectionSQL.AgregarDB;
import ConnectionSQL.ConsultasVarias;
import ConnectionSQL.ModDB;
import static Frontend.SignEmp.tienda_actual;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chejohrpp
 */
public class NewVenta extends javax.swing.JFrame {
     private DefaultTableModel dfm = new DefaultTableModel();
    private double total;
    private double cred;
    private LinkedList cod = new LinkedList();
    private LinkedList cant = new LinkedList();
    private LinkedList exisst = new LinkedList();

    /**
     * Creates new form NewVenta
     */
    public NewVenta() {
        initComponents();
        agregarProd();
        agregarNIt();
        agregarRes();
        dfm = (DefaultTableModel) jList.getModel();
    }
    private void agregarProd(){
        cmbProd.removeAllItems();
        ConsultasVarias consulta = new ConsultasVarias();
        LinkedList productos = consulta.codProds(tienda_actual);
        while(productos.peek() != null){
            String data = (String) productos.poll();
            cmbProd.addItem(data);
        }
    }
    private void agregarNIt(){
        cmbClient.removeAllItems();
        ConsultasVarias consulta = new ConsultasVarias();
        LinkedList nit = consulta.nitClient();
        while(nit.peek() != null){
            String data = (String) nit.poll();
            cmbClient.addItem(data);
        }
    }
    private void agregarRes(){
        ConsultasVarias consulta = new ConsultasVarias();
        lblExist.setText(String.valueOf("Existencias: "+consulta.exist(tienda_actual, cmbProd.getSelectedItem().toString())));
        cred = consulta.cred(cmbClient.getSelectedItem().toString());
        lblCred.setText(String.valueOf("Credito máximo del cliente: "+cred));
        lblPrecio.setText("Precio: "+String.valueOf(consulta.precio(cmbProd.getSelectedItem().toString())));
    }
    private void generar(){        
        //Agregar listado
        try{
            ConsultasVarias consulta = new ConsultasVarias();
             int cantidad = Integer.parseInt(txtCant.getText());
             int exist = consulta.exist(tienda_actual,cmbProd.getSelectedItem().toString());
            if (cantidad <= exist) {
                cod.offer(cmbProd.getSelectedItem().toString());          
                cant.offer(cantidad);
                int rest = exist-cantidad;
                exisst.offer(rest);
                calc(cantidad,consulta.precio(cmbProd.getSelectedItem().toString()));
                String data[] = {cmbProd.getSelectedItem().toString(),String.valueOf(consulta.precio(cmbProd.getSelectedItem().toString())),String.valueOf(cantidad)};
                dfm.addRow(data);
            }else{
                JOptionPane.showMessageDialog(null, "No hay muchas existencias", "ERORR", JOptionPane.ERROR_MESSAGE);
            }
            
        } catch(Exception e){
           JOptionPane.showMessageDialog(null, "Ingrese los datos", "ERORR", JOptionPane.ERROR_MESSAGE);  

        }      
        
    }
        private void calc(int cant, double precio){
        total += cant*precio;
        
        
        lblTotal.setText("Total: " + String.valueOf(total));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList = new javax.swing.JTable();
        cmbClient = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cmbProd = new javax.swing.JComboBox<>();
        txtEfect = new javax.swing.JTextField();
        txtCred = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCant = new javax.swing.JTextField();
        lblExist = new javax.swing.JLabel();
        bntAdd = new javax.swing.JButton();
        lblCred = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnConfirm = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        lblPrecio = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabel8.setText("Cliente");

        jList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Cantidad", "Precio"
            }
        ));
        jList.setToolTipText("");
        jScrollPane1.setViewportView(jList);

        cmbClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbClientActionPerformed(evt);
            }
        });

        jLabel2.setText("Producto");

        cmbProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProdActionPerformed(evt);
            }
        });

        jLabel3.setText("Cantidad");

        txtCant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantActionPerformed(evt);
            }
        });

        lblExist.setText("Existencia: 987");

        bntAdd.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        bntAdd.setText("Agregar");
        bntAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAddActionPerformed(evt);
            }
        });

        lblCred.setText("credito Maximo: 000");

        jLabel6.setText("Pago en efectivo");

        btnConfirm.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        btnConfirm.setText("Confirmar");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        jLabel7.setText("Pago con credito");

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel1.setText("Realizar Venta");

        btnRegresar.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        lblPrecio.setText("Precio:000");

        lblTotal.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblTotal.setText("Total:000");

        jLabel4.setText("Coloque 0 si no va a pagar en una casilla");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(btnConfirm)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRegresar)
                                .addGap(6, 6, 6))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblPrecio)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblExist))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(lblCred)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(cmbProd, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtEfect)
                                    .addComponent(txtCred)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtCant)
                                        .addGap(6, 6, 6)))))
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(196, 196, 196)
                                .addComponent(bntAdd))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(181, 181, 181)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(cmbClient, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblTotal)
                                        .addGap(255, 255, 255))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(108, 108, 108)))))))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel1)
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cmbProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCant, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblExist)
                            .addComponent(lblPrecio))
                        .addGap(34, 34, 34)
                        .addComponent(bntAdd)
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cmbClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtEfect))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtCred))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCred)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addComponent(lblTotal)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnConfirm)
                            .addComponent(btnRegresar)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        OpcionEmp emp = new OpcionEmp();
        emp.setLocationRelativeTo(null);
        emp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void bntAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAddActionPerformed
        // TODO add your handling code here:
        generar();
    }//GEN-LAST:event_bntAddActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        // TODO add your handling code here:
        try{
            double quitCred = Double.parseDouble(txtCred.getText());
            double efect = Double.parseDouble(txtEfect.getText());
            double ant = quitCred+efect;
            
            if (quitCred <= cred) {
                if (ant == total) {
                    AgregarDB agregar = new AgregarDB();  
                    agregar.addVenta(cmbClient.getSelectedItem().toString(), total);
                     ConsultasVarias consulta = new ConsultasVarias();
                     int cod_ped = consulta.lastVenta();
                    while(cod.peek() != null){
                        AgregarDB agregar1 = new AgregarDB();                          
                        agregar1.addArtVenta((int)cant.poll(), cod_ped, (String)cod.poll(), (int)exisst.poll());
                    }                    
                    ModDB mod = new ModDB();
                    mod.modCred(cred-quitCred, cmbClient.getSelectedItem().toString());
                    
                    //JOptionPane.showMessageDialog(null, "Pedido confirmado", "Finalizado Exitoso", JOptionPane.INFORMATION_MESSAGE);
                    OpcionEmp emp = new OpcionEmp();
                    emp.setLocationRelativeTo(null);
                    emp.setVisible(true);
                    this.dispose();
                }else{
                    JOptionPane.showMessageDialog(null, "No es la cantidad correcta", "ERORR", JOptionPane.ERROR_MESSAGE);
                }        
            }else{
                JOptionPane.showMessageDialog(null, "supera el limite de uso en el credito", "ERORR", JOptionPane.ERROR_MESSAGE);
            }
        }catch(Exception e){
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(null, "no se ha podido completar la tarea, verifique los datos", "ERORR", JOptionPane.ERROR_MESSAGE);  
        }
        
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void cmbClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbClientActionPerformed
        // TODO add your handling code here:
        if (cmbClient.getSelectedIndex() != -1) {
            ConsultasVarias consulta = new ConsultasVarias();
            cred = consulta.cred(cmbClient.getSelectedItem().toString());
            lblCred.setText(String.valueOf("Credito máximo del cliente: "+cred));
        }
    }//GEN-LAST:event_cmbClientActionPerformed

    private void cmbProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProdActionPerformed
        // TODO add your handling code here:
        if (cmbProd.getSelectedIndex() != -1) {
            ConsultasVarias consulta = new ConsultasVarias();
            lblExist.setText(String.valueOf("Existencias: "+consulta.exist(tienda_actual, cmbProd.getSelectedItem().toString())));
            lblPrecio.setText("Precio: "+String.valueOf(consulta.precio(cmbProd.getSelectedItem().toString())));
        }
    }//GEN-LAST:event_cmbProdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntAdd;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cmbClient;
    private javax.swing.JComboBox<String> cmbProd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTable jList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCred;
    private javax.swing.JLabel lblExist;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTextField txtCant;
    private javax.swing.JTextField txtCred;
    private javax.swing.JTextField txtEfect;
    // End of variables declaration//GEN-END:variables
}
