/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontend;

import ConnectionSQL.ConnectionDB;
import Frontend.Listados.ListadosGeneral;
import Frontend.Reportes.ReportGeneral;
import static Frontend.SignEmp.emp_actual;
import static Frontend.SignEmp.nombre_tienda_a;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author chejohrpp
 */
public class OpcionEmp extends javax.swing.JFrame {

    /**
     * Creates new form OpcionEmp
     */
    public OpcionEmp() {
        initComponents();
        btnSalirExit.setForeground(Color.red);
        
        lblNameT.setText(nombre_tienda_a);
        
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnModTienda = new javax.swing.JButton();
        btnNewProducto = new javax.swing.JButton();
        btnNewTIenda = new javax.swing.JButton();
        btnNewCliente = new javax.swing.JButton();
        btnModCliente = new javax.swing.JButton();
        btnModProducto = new javax.swing.JButton();
        btnNewTiempo = new javax.swing.JButton();
        btnModEmp = new javax.swing.JButton();
        btnNewEmpleado = new javax.swing.JButton();
        btnReaPedido = new javax.swing.JButton();
        btnverPedido = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        btnReaVentas = new javax.swing.JButton();
        btnRePedido = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblNameT = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        btnSalirExit = new javax.swing.JButton();
        btnLista = new javax.swing.JButton();
        btnLista1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel1.setText("Agregar");

        btnModTienda.setText("Modificar tienda");
        btnModTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModTiendaActionPerformed(evt);
            }
        });

        btnNewProducto.setText("Agregar Producto");
        btnNewProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewProductoActionPerformed(evt);
            }
        });

        btnNewTIenda.setText("Agregar Tienda");
        btnNewTIenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewTIendaActionPerformed(evt);
            }
        });

        btnNewCliente.setText("Agregar Cliente");
        btnNewCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewClienteActionPerformed(evt);
            }
        });

        btnModCliente.setText("Modificar Cliente");
        btnModCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModClienteActionPerformed(evt);
            }
        });

        btnModProducto.setText("Modificar Producto");
        btnModProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModProductoActionPerformed(evt);
            }
        });

        btnNewTiempo.setText("Editar Tiempos de Envios");
        btnNewTiempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewTiempoActionPerformed(evt);
            }
        });

        btnModEmp.setText("Modificar Empleado");
        btnModEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModEmpActionPerformed(evt);
            }
        });

        btnNewEmpleado.setText("Agregar Empleado");
        btnNewEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewEmpleadoActionPerformed(evt);
            }
        });

        btnReaPedido.setText("Realizar Pedido");
        btnReaPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReaPedidoActionPerformed(evt);
            }
        });

        btnverPedido.setText("Verificar Pedidos");
        btnverPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnverPedidoActionPerformed(evt);
            }
        });

        btnReportes.setText("Reportes");
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });

        btnReaVentas.setText("Realizar Ventas");
        btnReaVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReaVentasActionPerformed(evt);
            }
        });

        btnRePedido.setText("Registrar Pedidos");
        btnRePedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRePedidoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel2.setText("Varios");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel3.setText("Modificar");

        lblNameT.setFont(new java.awt.Font("Ubuntu", 0, 48)); // NOI18N
        lblNameT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNameT.setText("TIENDA 'A'");

        btnCerrar.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        btnCerrar.setText("Cerrar Sesion");
        btnCerrar.setOpaque(true);
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        btnSalirExit.setBackground(new java.awt.Color(220, 19, 19));
        btnSalirExit.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        btnSalirExit.setText("Salir del Programa");
        btnSalirExit.setOpaque(true);
        btnSalirExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirExitActionPerformed(evt);
            }
        });

        btnLista.setText("Listados");
        btnLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaActionPerformed(evt);
            }
        });

        btnLista1.setText("Agregar existencias en producto");
        btnLista1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLista1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNewProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107)
                        .addComponent(btnModProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108)
                        .addComponent(btnverPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnNewEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNewCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(107, 107, 107)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnModEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnModCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(108, 108, 108)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnReaVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNewTIenda, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNameT, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnModTienda, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(108, 108, 108)
                                .addComponent(btnRePedido, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnLista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnReportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNewTiempo, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE))
                    .addComponent(btnLista1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel1)
                .addGap(186, 186, 186)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(224, 224, 224))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSalirExit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCerrar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCerrar)
                    .addComponent(btnSalirExit))
                .addGap(18, 18, 18)
                .addComponent(lblNameT)
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNewTIenda, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModTienda, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnRePedido, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnNewTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(btnNewProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnModProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(btnverPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNewCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnNewEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnModCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnModEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnLista1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLista, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnReaVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRePedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRePedidoActionPerformed
        // TODO add your handling code here:
        RePedido re = new RePedido();
        re.setLocationRelativeTo(null);
        re.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnRePedidoActionPerformed

    private void btnNewTIendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewTIendaActionPerformed
        // TODO add your handling code here:
        NewTienda crear_tienda = new NewTienda();
        crear_tienda.setLocationRelativeTo(null);
        crear_tienda.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnNewTIendaActionPerformed

    private void btnNewTiempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewTiempoActionPerformed
        // TODO add your handling code here:
        NewTiempo tiempo = new NewTiempo();
        tiempo.setLocationRelativeTo(null);
        tiempo.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnNewTiempoActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        SignEmp sign = new SignEmp();
        sign.setLocationRelativeTo(null);
        this.dispose();
        sign.setVisible(true);
        
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnNewProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewProductoActionPerformed
        // TODO add your handling code here:
        NewProducto producto = new NewProducto();
        producto.setLocationRelativeTo(null);
        producto.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnNewProductoActionPerformed

    private void btnNewClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewClienteActionPerformed
        // TODO add your handling code here:
        NewCliente tiempo = new NewCliente();
        tiempo.setLocationRelativeTo(null);
        tiempo.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnNewClienteActionPerformed

    private void btnNewEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewEmpleadoActionPerformed
        // TODO add your handling code here:
        NewEmp empleado = new NewEmp();
        empleado.setLocationRelativeTo(null);
        empleado.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnNewEmpleadoActionPerformed

    private void btnSalirExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);        
    }//GEN-LAST:event_btnSalirExitActionPerformed

    private void btnModTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModTiendaActionPerformed
        // TODO add your handling code here:
        NewTienda tienda =  new NewTienda("  Modificar Tienda");
        this.setVisible(false);
//        tienda.setLocationRelativeTo(null);
//        tienda.setVisible(true);
        
    }//GEN-LAST:event_btnModTiendaActionPerformed

    private void btnModProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModProductoActionPerformed
        // TODO add your handling code here:
         NewProducto producto = new NewProducto("   Modificar Producto");
         this.setVisible(false);
        
    }//GEN-LAST:event_btnModProductoActionPerformed

    private void btnModClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModClienteActionPerformed
        // TODO add your handling code here:
        NewCliente tiempo = new NewCliente("   Modificar Cliente");
        this.setVisible(false);
    }//GEN-LAST:event_btnModClienteActionPerformed

    private void btnModEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModEmpActionPerformed
        // TODO add your handling code here:
        NewEmp empleado = new NewEmp("   Modificar Empleado");
        this.setVisible(false);
    }//GEN-LAST:event_btnModEmpActionPerformed

    private void btnLista1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLista1ActionPerformed
        // TODO add your handling code here:
        NewArt art = new NewArt();
        this.setVisible(false);
    }//GEN-LAST:event_btnLista1ActionPerformed

    private void btnListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaActionPerformed
        // TODO add your handling code here:
        ListadosGeneral lista = new ListadosGeneral();
        lista.setLocationRelativeTo(null);
        lista.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnListaActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        // TODO add your handling code here:
        ReportGeneral report = new ReportGeneral();
        report.setLocationRelativeTo(null);
        report.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnReportesActionPerformed

    private void btnverPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnverPedidoActionPerformed
        // TODO add your handling code here:
        ConPedido con = new ConPedido();
        con.setLocationRelativeTo(null);
        con.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnverPedidoActionPerformed

    private void btnReaVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReaVentasActionPerformed
        // TODO add your handling code here:
        NewVenta venta = new NewVenta();
        venta.setLocationRelativeTo(null);
        venta.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnReaVentasActionPerformed

    private void btnReaPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReaPedidoActionPerformed
        // TODO add your handling code here:
        NewPedido pedido = new NewPedido();
        pedido.setLocationRelativeTo(null);
        pedido.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnReaPedidoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnLista;
    private javax.swing.JButton btnLista1;
    private javax.swing.JButton btnModCliente;
    private javax.swing.JButton btnModEmp;
    private javax.swing.JButton btnModProducto;
    private javax.swing.JButton btnModTienda;
    private javax.swing.JButton btnNewCliente;
    private javax.swing.JButton btnNewEmpleado;
    private javax.swing.JButton btnNewProducto;
    private javax.swing.JButton btnNewTIenda;
    private javax.swing.JButton btnNewTiempo;
    private javax.swing.JButton btnRePedido;
    private javax.swing.JButton btnReaPedido;
    private javax.swing.JButton btnReaVentas;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnSalirExit;
    private javax.swing.JButton btnverPedido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblNameT;
    // End of variables declaration//GEN-END:variables
}
