/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontend;
import ConnectionSQL.AgregarDB;
import ConnectionSQL.ConnectionDB;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author chejohrpp
 */
public class SignEmp extends javax.swing.JFrame {
    ConnectionDB con = new ConnectionDB();
    Connection connection;
    //datos que seran utilizados ṕara toda la sesion
    public static String emp_actual;
    public static String tienda_actual;
    public static String nombre_tienda_a;
    /**
     * Creates new form signEmp
     */
    public SignEmp() {
        this.setUndecorated(true);
        initComponents();
        connection = con.getConnection();
        llenarCmb();
    }
    //llenamos el JcomboBox con los nombres de la tienda
    private void llenarCmb(){
        String query = "SELECT nombre FROM tienda";
        try(PreparedStatement preSt = connection.prepareStatement(query)){
            ResultSet result = preSt.executeQuery();
            while(result.next()){
                cmbTienda.addItem(result.getString(1));
            }
            result.close();
            con.closeConnection();
        }catch(SQLException e){
            
        }
    }
    //buscamos el codigo de la tienda
    private void codTienda(String nombre){
        ConnectionDB con = new ConnectionDB();
        Connection connection = con.getConnection();
        String query = "SELECT codigo from tienda WHERE nombre= ?";
        try(PreparedStatement preSt = connection.prepareStatement(query)){
            preSt.setString(1, nombre);
            
            ResultSet result = preSt.executeQuery();            
            
            if (result.next()) {
                tienda_actual = result.getString(1);
                //System.out.println(tienda_actual);
            } 
            result.close();
            con.closeConnection();
        }catch(SQLException e){
            System.out.println(e.getMessage());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNameEmp = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnSignUp = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cmbTienda = new javax.swing.JComboBox<>();
        btnBack = new javax.swing.JButton();
        txtPass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jLabel1.setText("Inicio de sesion de empleados");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel2.setText("Nombre");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel3.setText("Codigo de empleado");

        btnSignUp.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        btnSignUp.setText("Ingresar");
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel4.setText("Tienda");

        btnBack.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        btnBack.setText("Regresar");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                                .addComponent(txtNameEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(27, 27, 27))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(60, 60, 60)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbTienda, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtPass)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addComponent(btnSignUp)
                        .addGap(54, 54, 54)
                        .addComponent(btnBack)))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel1)
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNameEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbTienda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSignUp)
                    .addComponent(btnBack))
                .addGap(61, 61, 61))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Vemos si podemos iniciar sesion
    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        // TODO add your handling code here:
        try{
        String cod_empleado = String.valueOf(txtPass.getPassword());
        String nombre_empleado = txtNameEmp.getText();       
        nombre_tienda_a = cmbTienda.getSelectedItem().toString();
        codTienda(nombre_tienda_a);
        boolean verificar = verificarIngreso(cod_empleado,nombre_empleado);
            if (verificar) {
                AgregarDB agregar = new AgregarDB();
                agregar.addSign(emp_actual, tienda_actual);
                this.setVisible(false);
                OpcionEmp opcion = new OpcionEmp();
                opcion.setLocationRelativeTo(null);
                opcion.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(null, "Usuario no encontrado \nIntentalo de nuevo");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, " Valores ingresados incorrectamente \n vuelva a ingresarlos");
        }
    }//GEN-LAST:event_btnSignUpActionPerformed

    //Verificamos que el empleado exista y llenamos variables globales
    private boolean verificarIngreso(String cod,String nombre){
        ConnectionDB con = new ConnectionDB();
        Connection connection = con.getConnection();
        String query = "SELECT COUNT(*) FROM empleado Where nombre= ? and codigo = ?";
        try(PreparedStatement preSt = connection.prepareStatement(query)){
            preSt.setString(1, nombre);
            preSt.setString(2, cod);
            ResultSet result = preSt.executeQuery();
            if (result.next()) {
                if (Integer.parseInt(result.getString(1)) == 1) {
                    emp_actual = cod;                     
                    con.closeConnection();
                    return true;
                }
            }             
            con.closeConnection();
        }catch(SQLException e){
            System.out.println(e.getMessage());
        }
        return false;
    }
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Inicio inicio = new Inicio();
        inicio.setLocationRelativeTo(null);
        inicio.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JComboBox<String> cmbTienda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtNameEmp;
    private javax.swing.JPasswordField txtPass;
    // End of variables declaration//GEN-END:variables
}
