/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontend.Reportes;

import ConnectionSQL.ConnectionDB;
import ConnectionSQL.Reportes;
import Frontend.OpcionEmp;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chejohrpp
 */
public class R5 extends javax.swing.JInternalFrame {
    private String cli;
    private DefaultTableModel dfm = new DefaultTableModel();
    private LinkedList nit = new LinkedList();
    private LinkedList name = new LinkedList();
    private LinkedList cant = new LinkedList();

    /**
     * Creates new form R5
     */
    public R5() {
        initComponents();
        dfm = (DefaultTableModel) jList.getModel();
        
        buscarCli();  
        Reportes rep = new Reportes();
        rep.report5(cli, nit, name, cant);
        generar();
        this.show();
    }
    private void generar(){
         //Limpiar listado
       int cantRow = jList.getRowCount();
        for (int i = cantRow-1; i >= 0; i--) {
            dfm.removeRow(i);
        }
        
        //Agregar listado
        while (nit.peek() != null) {            
                String data[] = {(String)nit.poll(),(String)name.poll(),(String)cant.poll()};
                dfm.addRow(data);
        }
        
    }
    private void buscarCli(){
        ConnectionDB con = new ConnectionDB();       
        try( Connection connection = con.getConnection()){
            String query = "SELECT nit FROM cliente"; 
            
            try(PreparedStatement preSt = connection.prepareStatement(query)){
                ResultSet result = preSt.executeQuery();
                JComboBox camCliente = new JComboBox();//creamos un JComboBox
                //agregamos los nombres al JComboBox
                while(result.next()){
                    camCliente.addItem(result.getString(1));
                }
                //hacemos que el usuario seleccione el NIT del cliente
                //camCliente.setEditable(true);
                JOptionPane.showMessageDialog(null, camCliente, "Seleccione el NIT del cliente", JOptionPane.QUESTION_MESSAGE);
                 cli = camCliente.getSelectedItem().toString();                
                result.close();
                //con.closeConnection();//cerramos conexion
            }catch(SQLException e){
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(OpcionEmp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList = new javax.swing.JTable();

        setClosable(true);
        setTitle("Reporte todas las compras realizadas por un cliente.");

        jList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIT", "Nombre", "cantidad"
            }
        ));
        jScrollPane1.setViewportView(jList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable jList;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
