/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontend.Reportes;

import Frontend.OpcionEmp;

/**
 *
 * @author chejohrpp
 */
public class ReportGeneral extends javax.swing.JFrame {

    /**
     * Creates new form ReportGeneral
     */
    public ReportGeneral() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dpOnly = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        report1 = new javax.swing.JMenuItem();
        report2 = new javax.swing.JMenuItem();
        report3 = new javax.swing.JMenuItem();
        report4 = new javax.swing.JMenuItem();
        report5 = new javax.swing.JMenuItem();
        report6 = new javax.swing.JMenuItem();
        report7 = new javax.swing.JMenuItem();
        report8 = new javax.swing.JMenuItem();
        report9 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        limpiar = new javax.swing.JMenuItem();
        salir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuBar1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jMenuBar1.setMinimumSize(new java.awt.Dimension(60, 22));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(60, 26));

        jMenu1.setText("Reportes");
        jMenu1.setAutoscrolls(true);
        jMenu1.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N

        report1.setText("Reporte de pedidos en la tienda");
        report1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                report1ActionPerformed(evt);
            }
        });
        jMenu1.add(report1);

        report2.setText("Reportes pedido que están en tiempo de estar en la tienda pero debe verificarse su ingreso.");
        report2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                report2ActionPerformed(evt);
            }
        });
        jMenu1.add(report2);

        report3.setText("Reporte de todos los pedidos atrasados que llegarán a la tienda");
        report3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                report3ActionPerformed(evt);
            }
        });
        jMenu1.add(report3);

        report4.setText("Reporte  de todos los pedidos que salieron de la tienda y están en tránsito.");
        report4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                report4ActionPerformed(evt);
            }
        });
        jMenu1.add(report4);

        report5.setText("Reporte todas las compras realizadas por un cliente.");
        report5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                report5ActionPerformed(evt);
            }
        });
        jMenu1.add(report5);

        report6.setText("Reporte  todos los pedidos en curso de un cliente.");
        report6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                report6ActionPerformed(evt);
            }
        });
        jMenu1.add(report6);

        report7.setText("Reporte de los diez productos más vendidos en un intervalo de tiempo. ");
        jMenu1.add(report7);

        report8.setText("Reporte  de los productos más vendidos por tienda en un intervalo de tiempo. ");
        jMenu1.add(report8);

        report9.setText("Reportes de productos que nunca se han vendido por tienda.");
        jMenu1.add(report9);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Opciones");
        jMenu2.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N

        limpiar.setText("Limpiar");
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });
        jMenu2.add(limpiar);

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        jMenu2.add(salir);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpOnly, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1112, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpOnly, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void report2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_report2ActionPerformed
        // TODO add your handling code here:
        R2 r2 = new R2();
        this.dpOnly.add(r2);
        r2.setBounds(this.dpOnly.getBounds());
        r2.show();
    }//GEN-LAST:event_report2ActionPerformed

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        // TODO add your handling code here:
        this.dpOnly.removeAll();
        this.dpOnly.repaint();
    }//GEN-LAST:event_limpiarActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        OpcionEmp emp = new OpcionEmp();
        emp.setLocationRelativeTo(null);
        emp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_salirActionPerformed

    private void report1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_report1ActionPerformed
        // TODO add your handling code here:
        R1PedTI r1 = new R1PedTI();
        this.dpOnly.add(r1);
        r1.setBounds(this.dpOnly.getBounds());
        r1.show();
    }//GEN-LAST:event_report1ActionPerformed

    private void report3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_report3ActionPerformed
        // TODO add your handling code here:
        R3 r3 = new R3();
        this.dpOnly.add(r3);
        r3.setBounds(this.dpOnly.getBounds());
        r3.show();
    }//GEN-LAST:event_report3ActionPerformed

    private void report4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_report4ActionPerformed
        // TODO add your handling code here:
        R4 r4 = new R4();
        this.dpOnly.add(r4);
        r4.setBounds(this.dpOnly.getBounds());
        r4.show();
    }//GEN-LAST:event_report4ActionPerformed

    private void report5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_report5ActionPerformed
        // TODO add your handling code here:
        R5 r5 = new R5();
        this.dpOnly.add(r5);
        r5.setBounds(this.dpOnly.getBounds());
    }//GEN-LAST:event_report5ActionPerformed

    private void report6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_report6ActionPerformed
        // TODO add your handling code here:
        R6 r6 = new R6();
        this.dpOnly.add(r6);
        r6.setBounds(this.dpOnly.getBounds());
    }//GEN-LAST:event_report6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dpOnly;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem limpiar;
    private javax.swing.JMenuItem report1;
    private javax.swing.JMenuItem report2;
    private javax.swing.JMenuItem report3;
    private javax.swing.JMenuItem report4;
    private javax.swing.JMenuItem report5;
    private javax.swing.JMenuItem report6;
    private javax.swing.JMenuItem report7;
    private javax.swing.JMenuItem report8;
    private javax.swing.JMenuItem report9;
    private javax.swing.JMenuItem salir;
    // End of variables declaration//GEN-END:variables
}
