/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontend.Listados;

import Frontend.OpcionEmp;

/**
 *
 * @author chejohrpp
 */
public class ListadosGeneral extends javax.swing.JFrame {

    /**
     * Creates new form ListadosGeneral
     */
    public ListadosGeneral() {
        initComponents();
        //this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dpOnly = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        listTienda = new javax.swing.JMenuItem();
        listTime = new javax.swing.JMenuItem();
        listProd = new javax.swing.JMenuItem();
        listEmp = new javax.swing.JMenuItem();
        listClie = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jMenuBar1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N

        jMenu1.setText("Listado");

        listTienda.setText("Listado de tienda");
        listTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listTiendaActionPerformed(evt);
            }
        });
        jMenu1.add(listTienda);

        listTime.setText("Listado tiempo");
        listTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listTimeActionPerformed(evt);
            }
        });
        jMenu1.add(listTime);

        listProd.setText("Listado Productos");
        listProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listProdActionPerformed(evt);
            }
        });
        jMenu1.add(listProd);

        listEmp.setText("Listado de Empleados");
        listEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listEmpActionPerformed(evt);
            }
        });
        jMenu1.add(listEmp);

        listClie.setText("Listado de Clientes");
        listClie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listClieActionPerformed(evt);
            }
        });
        jMenu1.add(listClie);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Opciones");

        jMenuItem2.setText("Limpiar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Salir");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpOnly, javax.swing.GroupLayout.DEFAULT_SIZE, 1223, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpOnly, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listTiendaActionPerformed
        // TODO add your handling code here:
        ListTiendas tienda = new ListTiendas();
        this.dpOnly.add(tienda);
        tienda.setBounds(this.dpOnly.getBounds());
        tienda.show();
    }//GEN-LAST:event_listTiendaActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        this.dpOnly.removeAll();
        this.dpOnly.repaint();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        OpcionEmp emp = new OpcionEmp();
        emp.setLocationRelativeTo(null);
        emp.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void listTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listTimeActionPerformed
        // TODO add your handling code here:
        ListTimes time = new ListTimes();
        this.dpOnly.add(time);
        time.setBounds(this.dpOnly.getBounds());
        time.show();
    }//GEN-LAST:event_listTimeActionPerformed

    private void listProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listProdActionPerformed
        // TODO add your handling code here:
        ListProd prod = new ListProd();
        this.dpOnly.add(prod);
        prod.setBounds(this.dpOnly.getBounds());
        prod.show();
    }//GEN-LAST:event_listProdActionPerformed

    private void listEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listEmpActionPerformed
        // TODO add your handling code here:
        ListEmp emp = new ListEmp();
        this.dpOnly.add(emp);
        emp.setBounds(this.dpOnly.getBounds());
        emp.show();
    }//GEN-LAST:event_listEmpActionPerformed

    private void listClieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listClieActionPerformed
        // TODO add your handling code here:
        ListClient cliente = new ListClient();
        this.dpOnly.add(cliente);
        cliente.setBounds(this.dpOnly.getBounds());
        cliente.show();
    }//GEN-LAST:event_listClieActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dpOnly;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem listClie;
    private javax.swing.JMenuItem listEmp;
    private javax.swing.JMenuItem listProd;
    private javax.swing.JMenuItem listTienda;
    private javax.swing.JMenuItem listTime;
    // End of variables declaration//GEN-END:variables
}
