/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontend.Listados;

import ConnectionSQL.Listados;
import java.util.LinkedList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chejohrpp
 */
public class ListProd extends javax.swing.JInternalFrame {
    private DefaultTableModel dfm = new DefaultTableModel();
    private LinkedList cod = new LinkedList();
    private LinkedList nom = new LinkedList();
    private LinkedList fab = new LinkedList();
    private LinkedList precio = new LinkedList();
    private LinkedList garant = new LinkedList();
    private LinkedList desc = new LinkedList();

    /**
     * Creates new form ListProd
     */
    public ListProd() {
        initComponents();
        
         dfm = (DefaultTableModel) jList.getModel();
        Listados lista = new Listados();
        lista.listProd(cod, nom, fab, precio, garant, desc);
        generar();
    }
    private void generar(){
         //Limpiar listado
       int cantRow = jList.getRowCount();
        for (int i = cantRow-1; i >= 0; i--) {
            dfm.removeRow(i);
        }
        
        //Agregar listado
        while (cod.peek() != null) {            
                String data[] = {(String)cod.poll(),(String)nom.poll(),(String)fab.poll(),(String)precio.poll(),
                    (String)garant.poll(),(String)desc.poll()};
                dfm.addRow(data);
        }
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnName = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnCod = new javax.swing.JButton();
        txtCod = new javax.swing.JTextField();
        btnTodos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList = new javax.swing.JTable();

        setClosable(true);
        setTitle("Lista de producto");

        jLabel1.setText("Buscar por nombre");

        btnName.setText("Buscar");
        btnName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNameActionPerformed(evt);
            }
        });

        jLabel2.setText("Buscar por codigo");

        btnCod.setText("Buscar");
        btnCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCodActionPerformed(evt);
            }
        });

        btnTodos.setText("Ver todos");
        btnTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTodosActionPerformed(evt);
            }
        });

        jList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Fabricante", "Precio", "Garantia", "Descripcion"
            }
        ));
        jScrollPane1.setViewportView(jList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnName)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCod)
                            .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(btnTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(71, 71, 71))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnName)
                .addGap(206, 206, 206)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCod)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, Short.MAX_VALUE)
                .addComponent(btnTodos)
                .addGap(51, 51, 51))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNameActionPerformed
        // TODO add your handling code here:
        try{
            String name = txtName.getText();
            Listados lista = new Listados();
            lista.listProdName(name, cod, nom, fab, precio, garant, desc);
            generar();
        }catch(Exception e){

        }
    }//GEN-LAST:event_btnNameActionPerformed

    private void btnCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCodActionPerformed
        // TODO add your handling code here:
        try{
            String cod1 = txtCod.getText();
            Listados lista = new Listados();
            lista.listProdCod(cod1, cod, nom, fab, precio, garant, desc);
            generar();
        }catch(Exception e){

        }
    }//GEN-LAST:event_btnCodActionPerformed

    private void btnTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTodosActionPerformed
        // TODO add your handling code here:
        Listados lista = new Listados();
        lista.listProd(cod, nom, fab, precio, garant, desc);
        generar();
    }//GEN-LAST:event_btnTodosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCod;
    private javax.swing.JButton btnName;
    private javax.swing.JButton btnTodos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTable jList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCod;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
